### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by ToadTWP666** [Azure/IntelligentEdgeHOL#3]
I downloaded Jetpack version 4.3. and was able to get the edgeAgent, edgeHub and YoloModule running. However when I issue the command sudo docker logs -f YoloModule       

 I see the following errors:
.
Error: Time:Mon Jun  8 15:05:07 2020 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:380 Failure: connect failure 111.
Error: Time:Mon Jun  8 15:05:07 2020 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:764 wait_for_connection failed
Error: Time:Mon Jun  8 15:05:07 2020 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STA^Z

Would using Jetpack V 4.2 make a difference i.e. eliminate this error?

**Comment by ToadTWP666** [comment]
This error is caused because a hard coded version of the edgeAgent and edgeHub are hard coded in the deployment_template.manifest.json file (version 1.0.8) which is incompatible with the IoTEdge runtime version  1.0.9.2.31573326.

systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0.8",
              "createOptions": {}
            }

**Comment by micuentadecasa** [comment]
Confirmed, for me, with Jetpack 4.3 and deepstream 4.01, I had to change the versions to 1.0 

 "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
